find_path(OPENSSL_INCLUDE_DIR openssl/opensslconf.h
  PATHS $ENV{IMPALA_TOOLCHAIN}/openssl-$ENV{IMPALA_OPENSSL_VERSION}/include
  NO_DEFAULT_PATH)

find_library(OPENSSL_CRYPTO_LIB NAMES crypto
  PATHS $ENV{IMPALA_TOOLCHAIN}/openssl-$ENV{IMPALA_OPENSSL_VERSION}/lib
  NO_DEFAULT_PATH)

find_library(OPENSSL_CRYPTO_STATIC_LIB NAMES libcrypto.a
  PATHS $ENV{IMPALA_TOOLCHAIN}/openssl-$ENV{IMPALA_OPENSSL_VERSION}/lib
  NO_DEFAULT_PATH)

find_library(OPENSSL_SSL_LIB NAMES ssl
  PATHS $ENV{IMPALA_TOOLCHAIN}/openssl-$ENV{IMPALA_OPENSSL_VERSION}/lib
  NO_DEFAULT_PATH)

find_library(OPENSSL_SSL_STATIC_LIB NAMES libssl.a
  PATHS $ENV{IMPALA_TOOLCHAIN}/openssl-$ENV{IMPALA_OPENSSL_VERSION}/lib
  NO_DEFAULT_PATH)


if (OPENSSL_LIB STREQUAL "OPENSSL_LIB-NOTFOUND" OR
    OPENSSL_SSL_LIB STREQUAL "OPENSSL_SSL_LIB-NOTFOUND")
  message(FATAL_ERROR "OpenSSL not found")
endif()

mark_as_advanced(
  OPENSSL_INCLUDE_DIR
  OPENSSL_CRYPTO_LIB
  OPENSSL_CRYPTO_STATIC_LIB
  OPENSSL_SSL_LIB
  OPENSSL_SSL_STATIC_LIB
)